-- Profils publics liés à auth.users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  email text unique,
  name text,
  avatar text,
  created_at timestamptz not null default now()
);

-- Posts
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  image_url text,
  created_at timestamptz not null default now(),
  constraint posts_content_or_image check (
    coalesce(nullif(trim(content), ''), '') <> '' or image_url is not null
  )
);

-- Likes (relation many-to-many)
create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

-- Commentaires
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint comments_content_not_empty check (coalesce(nullif(trim(content), ''), '') <> '')
);

-- Conversations (chat privé)
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint messages_content_not_empty check (coalesce(nullif(trim(content), ''), '') <> '')
);

-- Trigger pour créer automatiquement un profil à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, email, name, avatar)
  values (
    new.id,
    lower(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1))),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'avatar', 'https://i.pravatar.cc/150?u=' || new.id::text)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.touch_conversation_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.conversations
  set updated_at = now()
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists on_message_created_touch_conversation on public.messages;
create trigger on_message_created_touch_conversation
  after insert on public.messages
  for each row execute procedure public.touch_conversation_updated_at();

create or replace function public.is_conversation_member(_conversation_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = _conversation_id
      and cp.user_id = auth.uid()
  );
$$;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;

-- Durcissement des contraintes (idempotent)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_username_normalized'
  ) then
    alter table public.profiles
      add constraint profiles_username_normalized
      check (
        username = lower(username)
        and username ~ '^[a-z0-9_]{2,20}$'
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'posts_content_max_length'
  ) then
    alter table public.posts
      add constraint posts_content_max_length
      check (content is null or char_length(content) <= 2000);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'posts_image_url_max_length'
  ) then
    alter table public.posts
      add constraint posts_image_url_max_length
      check (image_url is null or char_length(image_url) <= 2048);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'comments_content_max_length'
  ) then
    alter table public.comments
      add constraint comments_content_max_length
      check (char_length(content) <= 500);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_content_max_length'
  ) then
    alter table public.messages
      add constraint messages_content_max_length
      check (char_length(content) <= 2000);
  end if;
end
$$;

-- Indexes de performance
create unique index if not exists profiles_username_lower_uniq
  on public.profiles (lower(username));

create index if not exists posts_created_at_idx
  on public.posts (created_at desc);

create index if not exists posts_author_created_idx
  on public.posts (author_id, created_at desc);

create index if not exists post_likes_user_idx
  on public.post_likes (user_id);

create index if not exists comments_post_created_idx
  on public.comments (post_id, created_at);

create index if not exists comments_author_created_idx
  on public.comments (author_id, created_at desc);

create index if not exists conversation_participants_user_idx
  on public.conversation_participants (user_id);

create index if not exists conversations_updated_at_idx
  on public.conversations (updated_at desc);

create index if not exists messages_conversation_created_idx
  on public.messages (conversation_id, created_at);

create index if not exists messages_author_created_idx
  on public.messages (author_id, created_at desc);

-- Policies profiles
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles
  for select using (true);

drop policy if exists "profiles insert self" on public.profiles;
create policy "profiles insert self" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "profiles update self" on public.profiles;
create policy "profiles update self" on public.profiles
  for update using (auth.uid() = id);

-- Policies posts
drop policy if exists "posts readable" on public.posts;
create policy "posts readable" on public.posts
  for select using (true);

drop policy if exists "posts insert self" on public.posts;
create policy "posts insert self" on public.posts
  for insert with check (auth.uid() = author_id);

drop policy if exists "posts delete self" on public.posts;
create policy "posts delete self" on public.posts
  for delete using (auth.uid() = author_id);

-- Policies likes
drop policy if exists "likes readable" on public.post_likes;
create policy "likes readable" on public.post_likes
  for select using (true);

drop policy if exists "likes insert self" on public.post_likes;
create policy "likes insert self" on public.post_likes
  for insert with check (auth.uid() = user_id);

drop policy if exists "likes delete self" on public.post_likes;
create policy "likes delete self" on public.post_likes
  for delete using (auth.uid() = user_id);

-- Policies comments
drop policy if exists "comments readable" on public.comments;
create policy "comments readable" on public.comments
  for select using (true);

drop policy if exists "comments insert self" on public.comments;
create policy "comments insert self" on public.comments
  for insert with check (auth.uid() = author_id);

drop policy if exists "comments delete self" on public.comments;
create policy "comments delete self" on public.comments
  for delete using (auth.uid() = author_id);

-- Policies conversations
drop policy if exists "conversations member read" on public.conversations;
create policy "conversations member read" on public.conversations
  for select using (public.is_conversation_member(id));

drop policy if exists "conversations authenticated insert" on public.conversations;
create policy "conversations authenticated insert" on public.conversations
  for insert with check (auth.uid() is not null);

-- Policies conversation participants
drop policy if exists "participants member read" on public.conversation_participants;
create policy "participants member read" on public.conversation_participants
  for select using (public.is_conversation_member(conversation_id));

drop policy if exists "participants insert self" on public.conversation_participants;
create policy "participants insert self" on public.conversation_participants
  for insert with check (auth.uid() = user_id);

drop policy if exists "participants insert by member" on public.conversation_participants;
create policy "participants insert by member" on public.conversation_participants
  for insert with check (public.is_conversation_member(conversation_id));

-- Policies messages
drop policy if exists "messages member read" on public.messages;
create policy "messages member read" on public.messages
  for select using (public.is_conversation_member(conversation_id));

drop policy if exists "messages member insert" on public.messages;
create policy "messages member insert" on public.messages
  for insert with check (
    auth.uid() = author_id
    and public.is_conversation_member(conversation_id)
  );
